#应用端口
server:
  port: 8090
# 默认根路径
servlet:
  context-path: /hzed/qmqb-admin
spring:
  profiles:
    active: dev #环境
  application.name: qmqb-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.30.36:3306/easy_get_test3?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: rootroot
  #redis
  redis:
    database: 0
    host: 10.10.30.37
    port: 3037
    password: masterpass
    #key前缀
    prefix: ${spring.profiles.application.name}:${spring.profiles.active}

# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml # 配置文件路径
  longHome: D:/logs/qmqb-admin # 日志路径
  appName: 后台系统项目 # 应用名
  envName: 开发环境 # 环境名
  emailTo: wuchengwu@hzed.com # 邮件接收者，多个用逗号隔开

system:
  imgUploadPath: c:/imgUpload # 上传图片文件目录
  path: /C:/

# 阿里云配置 暂废弃
aliyun:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIxzelwCX3fyTQ
  accessKeySecret: IwfH6vAH0rZWK3wL2aK3hTopsWVb6t
  bucketName: hzed-ccard #存储空间目录
