#应用端口
server:
  port: 8090
# 默认根路径
servlet:
  context-path: /hzed/qmqb-admin
spring:
  profiles:
    active: dev #环境
    application.name: qmqb-admin
    datasouce:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.30.36:3306/easy_get_test3?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
      username: root
      psssword: rootroot
# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml # 配置文件路径
  longHome: D:/logs/qmqb-admin # 日志路径
  appName: 后台系统项目 # 应用名
  envName: 开发环境 # 环境名
  emailTo: 418085002@qq.com # 邮件接收者，多个用逗号隔开
